analyzer:
  errors:
    library_private_types_in_public_api: ignore
    prefer_single_quotes: ignore
    unnecessary_string_escapes: ignore
include: package:flutter_lints/flutter.yaml
formatter:
  page_width: 100
linter:
  rules:

    # Dart

    prefer_single_quotes: true
    prefer_relative_imports: true
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    prefer_final_locals: true
    no_duplicate_case_values: true
    prefer_const_constructors: true
    avoid_relative_lib_imports: true
    always_put_required_named_parameters_first : true
    avoid_init_to_null : true
    await_only_futures : true
    camel_case_extensions : true
    camel_case_types : true
    avoid_function_literals_in_foreach_calls : true

    # Flutter

    avoid_unnecessary_containers : true
    avoid_redundant_argument_values : true 

    